#!/bin/bash
# Converts a directory of markdown files into a directory of html files.

# if directory name html does not exist, make it.
if [ ! -d ./html ]
then
  mkdir html
  echo "Create directory name 'html'."
fi

# execute pandoc command for files passed as arguments.
files=( $@ )

for file in "${files[@]}"
do
    pandoc "$file" --highlight-style=kate --template=foundation.html5 -o "./html/${file%.md}.html";
done
